version: '3.9'
volumes:
  manguinho-mongo:
networks:
  manguinho-mongo:
services:
  db:
    image: mongo:4.4
    container_name: manguinho-mongo
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - manguinho-mongo:/data/db
    networks:
      - manguinho-mongo
  api:
    image: node:14.17.0
    container_name: manguinho-api
    restart: always
    volumes:
      - .:/api
    working_dir: /api
    networks:
      - manguinho-mongo
    depends_on: 
      - db
    command: bash -c "npm start"